### ISSUE TITLE
Maven repo resolution failure

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/mgmt#67]
Hi folks,

Attempting to build a raw image with "mgmt" included throws an error when trying to download the crash jar:

http://cloudius.artifactoryonline.com/cloudius/repo

This URL throws a 404, so I'm not sure if there's an issue with the existing build script or the repo has moved...

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Mon, Feb 16, 2015 at 12:00 PM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> Attempting to build a raw image with "mgmt" included throws an error when
> trying to download the crash jar:
>
> http://cloudius.artifactoryonline.com/cloudius/repo
>
> This URL throws a 404, so I'm not sure if there's an issue with the
> existing build script or the repo has moved...
>

Hi Rowland,

We stopped storing the repo on artifactory since we moved away from the
CRaSH shell
towards a c++ based RESTful api and a cli in Lua based on it. That's the
default image.

**Comment by yieldone** [comment]
Ahh, sorry missed that!

**Comment by rowlandwatkins** [comment]
Ahh, sorry, missed that! I'lll cross mgmt out for the time being - will mgmt be deprecated over time or does it still have a future role?

**Comment by tzach** [comment]
@rowlandwatkins moving forward we will invest in the REST API, and the CLI which use it, not in the CRaSH CLI.
